<!DOCTYPE html>
<html>
<head>
    <!-- <link rel="stylesheet" type="text/css" href="style.css"> -->
</head>
<body>
    <div class="container">
            <form method="post" action="HA.php">
                    <button name="Stop&start" value="start-stop">
                        <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100">
                            <path d="M8.122 24l-4.122-4 8-8-8-8 4.122-4 11.878 12z"/>
                        </svg>
                    </button>
                    <button name="Forward" value="up">
                        <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 80 80">
                            <path d="M8.122 24l-4.122-4 8-8-8-8 4.122-4 11.878 12z"/>
                        </svg>
                    </button>
                    <button name="Backward" value="down">
                        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 22.1 22.1" style="enable-background:new 0 0 22.1 22.1;" xml:space="preserve"> 
                            <path d="M11.1,22.1C11.1,22.1,11.1,22.1,11.1,22.1c-2.7,0-5.2-1-7.1-2.9C0.1,15.2,0.1,8.9,4,5c0.4-0.4,1-0.4,1.4,0 c0.4,0.4,0.4,1,0,1.4c-3.1,3.1-3.1,8.2,0,11.3c1.5,1.5,3.5,2.3,5.7,2.3c0,0,0,0,0,0c2.1,0,4.1-0.8,5.7-2.3c3.1-3.1,3.1-8.2,0-11.3 c-0.4-0.4-0.4-1,0-1.4c0.4-0.4,1-0.4,1.4,0c3.9,3.9,3.9,10.2,0,14.1C16.2,21,13.7,22.1,11.1,22.1z"/> 
                            <path d="M11.1,12.1c-0.6,0-1-0.4-1-1v-10c0-0.6,0.4-1,1-1s1,0.4,1,1v10C12.1,11.6,11.6,12.1,11.1,12.1z"/> 
                        </svg> 
                    </button>
                    <button name="Left" value="left">
                        <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 80 80">
                            <path d="M8.122 24l-4.122-4 8-8-8-8 4.122-4 11.878 12z"/>
                        </svg>
                    </button>
                    <button name="Right" value="right">
                        <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 80 80">
                            <path d="M8.122 24l-4.122-4 8-8-8-8 4.122-4 11.878 12z"/>
                        </svg>
                    </button>
            </form>
        </div>
        

</body>
</html>
